version: '3.0'

services:
  grafana:
    container_name: 'briangann-dotdiagram-panel'
    platform: "linux/amd64"
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.4.0}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/briangann-dotdiagram-panel
      - ./provisioning:/etc/grafana/provisioning
