name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check types
        run: yarn typecheck

      - name: Lint
        run: NODE_OPTIONS=--max_old_space_size=4096 yarn lint

      - name: Unit tests
        run: yarn test:ci

      - name: Build frontend
        run: yarn build

      - name: Check for backend
        id: check-for-backend
        run: |
          if [ -f "Magefile.go" ]
          then
            echo "has-backend=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup Go environment
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Test backend
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: coverage

      - name: Build backend
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: buildAll

      - name: Code Climate - Check environment
        id: check-for-codeclimate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          if [ ! -z $CC_TEST_REPORTER_ID ]
          then
            echo "has-codeclimate=true" >> $GITHUB_OUTPUT
          fi

      - name: Code Climate - Run
        if: steps.check-for-codeclimate.outputs.has-codeclimate == 'true'
        run: |
          mkdir -p ccbin/
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./ccbin/cc-test-reporter
          chmod +x ./ccbin/cc-test-reporter
          npm install -g jest jest-junit
          ./ccbin/cc-test-reporter format-coverage -t lcov -o out/codeclimate.frontend.json coverage/lcov.info
          npx jest --ci --runInBand --reporters=default --reporters=jest-junit

      - name: Code Climate - Upload
        if: steps.check-for-codeclimate.outputs.has-codeclimate == 'true'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          ./ccbin/cc-test-reporter sum-coverage out/codeclimate.*.json -d -p 1 -o out/codeclimate.total.json
          ./ccbin/cc-test-reporter upload-coverage -i out/codeclimate.total.json

      - name: E2E - Check for playwright
        id: e2e-check-for-playwright
        run: |
          if [ -d "playwright" ]
          then
            echo "has-e2e-playwright=true" >> $GITHUB_OUTPUT
          fi

      - name: E2E - Start Grafana in Docker
        if: steps.e2e-check-for-playwright.outputs.has-e2e-playwright == 'true'
        run: docker-compose up -d

      - name: E2E - Install playwright dependencies
        if: steps.e2e-check-for-playwright.outputs.has-e2e-playwright == 'true'
        run: sudo apt-get update && yarn playwright install --with-deps

      - name: E2E - Run tests
        id: e2e-run-tests
        if: steps.e2e-check-for-playwright.outputs.has-e2e-playwright == 'true'
        run: yarn run e2e:playwright

      - name: E2E - Stop Grafana in Docker
        if: steps.e2e-check-for-playwright.outputs.has-e2e-playwright == 'true'
        run: docker-compose down

      - name: E2E - Archive output
        uses: actions/upload-artifact@v4
        if: steps.e2e-check-for-playwright.outputs.has-e2e-playwright == 'true' && steps.e2e-run-tests.outcome != 'success'
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 5
